name: pr-checks

on:
  pull_request:

jobs:
  pr-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd app
          pip install -r requirements.txt

      - name: Run basic tests (placeholder)
        run: |
          cd app
          python -m compileall main.py

      - name: Upload CI logs and reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pr-checks-logs
          path: |
            **/pytest*.xml
            **/report*.json
            ${{ runner.temp }}/**/*.log
